use smartdns + adguard instead of adbyby

diff --git a/.github/workflows/K2P.yml b/.github/workflows/K2P.yml
--- a/.github/workflows/K2P.yml
+++ b/.github/workflows/K2P.yml
@@ -7,7 +7,7 @@ on:
     tags:
     - 'v*'
     branches: 
-      - own-master
+      - cloud-build
 #  schedule:
 #    - cron: 0 8 * * 5
   watch:
@@ -16,22 +16,33 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-    container: nldweowydd/padavan-build:latest
+    if: github.event.repository.owner.id == github.event.sender.id
 
     steps:
-    - name: Update repository
+    - name: Checkout
+      uses: actions/checkout@v3
+    - name: Initialization environment
+      env:
+        DEBIAN_FRONTEND: noninteractive
       run: |
-        cd /workspace/padavan-4.4
-        git fetch && git pull
-        mkdir -p /workspace/padavan-4.4/images
-    - name: Build firmware
+        sudo apt-get update
+        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
+        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
+        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
+    - name: Clone source code
+      run: |
+        git clone --depth=1 https://github.com/77160860/padavan-4.4.git /opt/rt-n56u
+        cd /opt/rt-n56u/toolchain-mipsel
+        sh dl_toolchain.sh
+        mkdir -p /opt/images/
+    - name: Build Firmware
       env:
         TNAME: K2P
       run: |
-        cd /workspace/padavan-4.4/trunk/
+        cd /opt/rt-n56u/trunk
         if [ ! -f configs/templates/$TNAME.config ] ; then
-          echo "configs/templates/$TNAME.config not found "
-          exit 1
+        echo "configs/templates/$TNAME.config not found "
+        exit 1
         fi
         cp -f configs/templates/$TNAME.config .config
         sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
@@ -61,7 +72,7 @@ jobs:
         echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config
         echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config
         echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> .config
+        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config
         echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config
         echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config
         echo "CONFIG_FIRMWARE_INCLUDE_XRAY=n" >> .config
@@ -69,7 +80,9 @@ jobs:
         echo "CONFIG_FIRMWARE_INCLUDE_DDNSTO=n" >> .config
         echo "CONFIG_FIRMWARE_INCLUDE_ALDRIVER=n" >> .config
         echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .confi
-        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config       
+        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config    
+        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config
+        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y" >> .config   
         
         ##QOS & CPU Overclocking##
         echo "CONFIG_FIRMWARE_INCLUDE_SQM=y" >> .config
